name: label
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cyrus-sasl=2.1.28
  - expat=2.7.1
  - freetype=2.13.3
  - gettext=0.21.0
  - icu=73.1
  - jpeg=9e
  - libabseil=20250127.0
  - libcurl=8.14.1
  - libcxx=17.0.6
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libglib=2.84.2
  - libiconv=1.16
  - libkrb5=1.21.3
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libssh2=1.11.1
  - libxml2=2.13.8
  - llvm-openmp=17.0.6
  - lmdb=0.9.29
  - lz4-c=1.9.4
  - mysql=8.4.0
  - ncurses=6.5
  - openldap=2.6.4
  - openssl=3.0.17
  - packaging=25.0
  - pcre2=10.42
  - pip=25.1
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - python=3.13.5
  - python_abi=3.13
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - readline=8.2
  - setuptools=78.1.1
  - sip=6.10.0
  - sqlite=3.50.2
  - tk=8.6.14
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - numpy==2.2.6
      - opencv-python-headless==4.12.0.88
      - pygments==2.19.2
      - pyqtdarktheme==0.1.7
      - qtpy==2.4.3
      - superqt==0.7.6
      - typing-extensions==4.15.0
      - ujson==5.10.0
      - imageio==2.37.0
prefix: /Users/chiehchiyang/miniconda3/envs/label
